[versions]
kotlin                         = "2.3.0-Beta2"
kotlinx-coroutines             = "1.10.2"
kotlinx-serialization          = "1.9.0"
ktor                           = "3.3.2 "
kotlin-logging                 = "7.0.13"
kotlin-cryptography            = "0.5.0"
kotlin-base32                  = "1.0.0"
slf4j                          = "2.1.0-alpha1"

[libraries]
kotlin-bom                           = { module = "org.jetbrains.kotlin:kotlin-bom"                                 , version.ref = "kotlin"}
kotlin-test                          = { module = "org.jetbrains.kotlin:kotlin-test"                                , version.ref = "kotlin"}
kotlinx-coroutines-bom               = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom"                    , version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core              = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"                   , version.ref = "kotlinx-coroutines"}
kotlinx-coroutines-test              = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"                   , version.ref = "kotlinx-coroutines"}
kotlinx-serialization-bom            = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom"                 , version.ref = "kotlinx-serialization" }
ktor-bom                             = { module = "io.ktor:ktor-bom"                                                , version.ref = "ktor"}
ktor-client-core                     = { module = "io.ktor:ktor-client-core"                                        , version.ref = "ktor"}
ktor-client-cio                      = { module = "io.ktor:ktor-client-cio"                                         , version.ref = "ktor"}
ktor-client-curl                     = { module = "io.ktor:ktor-client-curl"                                        , version.ref = "ktor"}
ktor-client-serialization            = { module = "io.ktor:ktor-client-serialization"                               , version.ref = "ktor"}
ktor-client-websockets               = { module = "io.ktor:ktor-client-websockets"                                  , version.ref = "ktor"}
ktor-client-content-negotiation      = { module = "io.ktor:ktor-client-content-negotiation"                         , version.ref = "ktor"}
ktor-client-auth                     = { module = "io.ktor:ktor-client-auth"                                        , version.ref = "ktor"}
ktor-client-logging                  = { module = "io.ktor:ktor-client-logging"                                     , version.ref = "ktor"}
ktor-client-resources                = { module = "io.ktor:ktor-client-resources"                                   , version.ref = "ktor"}
ktor-client-encoding                 = { module = "io.ktor:ktor-client-encoding"                                    , version.ref = "ktor"}
ktor-client-mock                     = { module = "io.ktor:ktor-client-mock"                                        , version.ref = "ktor"}
ktor-serialization-xml               = { module = "io.ktor:ktor-serialization-kotlinx-xml"                          , version.ref = "ktor"}
slf4j-simple                         = { module = "org.slf4j:slf4j-simple"                                          , version.ref = "slf4j"}
kotlin-logging                       = { module = "io.github.oshai:kotlin-logging"                                  , version.ref = "kotlin-logging"}
kotlin-cryptography-core             = { module = "dev.whyoleg.cryptography:cryptography-core"                      , version.ref = "kotlin-cryptography"}
kotlin-cryptography-optimal          = { module = "dev.whyoleg.cryptography:cryptography-provider-optimal"          , version.ref = "kotlin-cryptography"}
kotlin-base32                        = { module = "com.osmerion.kotlin:kotlin-base32"                               , version.ref = "kotlin-base32"}